import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Injectable()
export class UserService {

  mainInfo = [
    { id: 1, name: 'Derek Anderson', job: 'BRITISH COMEDIAN', video: '/assets/content/video_1.mp4', poster: '/assets/content/poster_1.jpg', title: 'ENQUIRE ABOUT DEREK' },
    { id: 2, name: 'Derek Dog', job: 'BRITISH Dog', video: '/assets/content/video_2.mp4', poster: '/assets/content/poster_2.jpg', title: 'ENQUIRE ABOUT DOG' },
    { id: 3, name: 'Derek Sea', job: 'BRITISH Sea', video: '/assets/content/video_3.mp4', poster: '/assets/content/poster_3.jpg', title: 'ENQUIRE ABOUT SEA' },
    { id: 4, name: 'Derek Desert', job: 'BRITISH Desert', video: '/assets/content/video_4.mp4', poster: '/assets/content/poster_4.jpg', title: 'ENQUIRE ABOUT Desert' }
  ];


  tabsData = [{
    id: 1, photo: ['/assets/content/seal_1.jpg', '/assets/content/seal_2.jpg', '/assets/content/seal_3.jpg', '/assets/content/seal_4.jpg'],
    data: [{ "tabName": "Profile.", "preview": "Derek Anderson is a leading actor, comedian and writer.", "award": "British Award 2020", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error sit vo- luptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam." },
    { "tabName": "Press.", "preview": "On press Derek Anderson is a leading comedian, actor and writer.", "award": "British Award 2018", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa." },
    { "tabName": "Awards.", "preview": "Awards of Derek Anderson is a million dollars.", "award": "British Award 2019", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error." },
    { "tabName": "Creadits.", "preview": "Don't know about Derek Anderson Creadits.", "award": "British Award 2021", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. " }]
  },
  {
    id: 2, photo: ['/assets/content/dog_1.jpg', '/assets/content/dog_2.jpg', '/assets/content/dog_3.jpg', '/assets/content/dog_4.jpg'],
    data: [{ "tabName": "Profile.", "preview": "Derek Dog is a leading actor, comedian and writer.", "award": "Dog Award 2020", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error sit vo- luptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam." },
    { "tabName": "Press.", "preview": "On press Derek Dog is a leading comedian, actor and writer.", "award": "Dog Award 2018", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa." },
    { "tabName": "Awards.", "preview": "Awards of Derek Dog is a million dollars.", "award": "Dog Award 2019", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error." },
    { "tabName": "Creadits.", "preview": "Don't know about Derek Dog Creadits.", "award": "Dog Award 2021", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. " }]
  },
  {
    id: 3, photo: ['/assets/content/sea_1.jpg', '/assets/content/sea_2.jpg', '/assets/content/sea_3.jpg', '/assets/content/sea_4.jpg'],
    data: [{ "tabName": "Profile.", "preview": "Derek Sea is a leading actor, comedian and writer.", "award": "Sea Award 2020", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error sit vo- luptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam." },
    { "tabName": "Press.", "preview": "On press Derek Sea is a leading comedian, actor and writer.", "award": "Sea Award 2018", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa." },
    { "tabName": "Awards.", "preview": "Awards of Derek Sea is a million dollars.", "award": "Sea Award 2019", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error." },
    { "tabName": "Creadits.", "preview": "Don't know about Derek Sea Creadits.", "award": "Sea Award 2021", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. " }]
  },
  {
    id: 4, photo: ['/assets/content/desert_1.jpg', '/assets/content/desert_2.jpg', '/assets/content/desert_3.jpg', '/assets/content/desert_4.jpg'],
    data: [{ "tabName": "Profile.", "preview": "Derek Desert is a leading actor, comedian and writer.", "award": "Desert Award 2020", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error sit vo- luptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam." },
    { "tabName": "Press.", "preview": "On press Derek Desert is a leading comedian, actor and writer.", "award": "Desert Award 2018", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa." },
    { "tabName": "Awards.", "preview": "Awards of Derek Desert is a million dollars.", "award": "Desert Award 2019", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est volaborum. Sed ut perspiciatis unde omnis iste natus error." },
    { "tabName": "Creadits.", "preview": "Don't know about Derek Desert Creadits.", "award": "Desert Award 2021", "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. " }]
  }];

  personInfo = [{
    id: 1,
    mainInfo: this.mainInfo.find(el => el.id == 1),
    about: this.tabsData.find(el => el.id == 1),
    onPress: this.tabsData.find(el => el.id == 1).photo,
    social: {}
  },
  {
    id: 2,
    mainInfo: this.mainInfo.find(el => el.id == 2),
    about: this.tabsData.find(el => el.id == 2),
    onPress: this.tabsData.find(el => el.id == 2).photo,
    social: {}
  },
  {
    id: 3,
    mainInfo: this.mainInfo.find(el => el.id == 3),
    about: this.tabsData.find(el => el.id == 3),
    onPress: this.tabsData.find(el => el.id == 3).photo,
    social: {}
  },
  {
    id: 4,
    mainInfo: this.mainInfo.find(el => el.id == 4),
    about: this.tabsData.find(el => el.id == 4),
    onPress: this.tabsData.find(el => el.id == 4).photo,
    social: {}
  }
  ];

  mockData = {
    landscapeData: [{ "id": 1, "name": "Вася", "job": "QA", "photo": "https://cdn-03.independent.ie/style/celebrity/celebrity-news/article37866116.ece/097c2/AUTOCROP/w620/ipanews_cbc3aeeb-0628-4b80-8370-0cd43cbc3929_1" }, { "id": 2, "name": "Петя", "job": "Developer", "photo": "https://pmctvline2.files.wordpress.com/2018/10/game-of-thrones-peter-dinklage-tyrion-death-season-8-interview.jpg?w=620" }, { "id": 3, "name": "Вова", "job": "Senior Developer", "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcaeIWOmi62oncorhSKDzoBPIA7mF1QWUqgnFXKRTbaGHAsp8fUA" }, { "id": 4, "name": "Арчибальд", "job": "QA Lead", "photo": "https://cdn-static.denofgeek.com/sites/denofgeek/files/styles/main_wide/public/2018/05/game-of-thrones-season-1-recap.jpg?itok=ZwQDxPFR" }, { "id": 5, "name": "Клава", "job": "PM", "photo": "https://media.socastsrm.com/wordpress/wp-content/blogs.dir/873/files/2019/04/game-of-thrones-character-poster.jpg" }, { "id": 6, "name": "Дуся", "job": "DM", "photo": "https://pmcvariety.files.wordpress.com/2017/12/game-of-thrones-sansa.jpg?w=1000&h=563&crop=1" }, { "id": 7, "name": "Саманта", "job": "BA", "photo": "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/lena-headey-cersei-lannister-game-of-thrones-season-8-1553173898.jpg?resize=480:*" }, { "id": 8, "name": "Ядвига", "job": "Junior QA", "photo": "https://www.hbo.com/content/dam/hbodata/series/game-of-thrones/episodes/8/episodes/69/ep69-gamerevealed-1920x1080.jpg/_jcr_content/renditions/cq5dam.web.1200.675.jpeg" }, { "id": 9, "name": "Акакий", "job": "DevOps", "photo": "https://dwgyu36up6iuz.cloudfront.net/heru80fdn/image/upload/c_fill,d_placeholder_wired.png,fl_progressive,g_face,h_450,q_80,w_800/v1389040063/wired_alfie-allen-on-game-of-thrones.jpg" }, { "id": 10, "name": "Нестор", "job": "DB Expert", "photo": "https://kor.ill.in.ua/m/610x385/2031772.jpg" }, { "id": 11, "name": "Потап", "job": "Solutions Architect", "photo": "https://vignette.wikia.nocookie.net/gameofthrones/images/9/94/804_Ghost_Profile.png/revision/latest/scale-to-width-down/338?cb=20190506030424" }, { "id": 12, "name": "Платон", "job": "DB Expert", "photo": "https://cdn.maximonline.ru/08/4c/23/084c235db5d0d0dc05c3168d89c30865/665x374_1_6c90704c7d93e73a7b220326b1e3f4f3@674x379_0xac120005_18077754021529114221.jpg" }, { "id": 13, "name": "Ефросинья", "job": "Frontend Developer", "photo": "https://cdnimg.rg.ru/i/gallery/a310d529/1_220c7ba8.jpg" }, { "id": 14, "name": "Джонатан", "job": "Backend Developer", "photo": "https://s14.stc.all.kpcdn.net/share/i/12/7983901/inx960x640.jpg" }, { "id": 15, "name": "Грег", "job": "Грег", "photo": "https://vignette.wikia.nocookie.net/warrior/images/4/4d/Jorah-mormont-01-683x1024.jpg/revision/latest?cb=20160221123449&path-prefix=ru" }, { "id": 1, "name": "Вася", "job": "QA", "photo": "https://cdn-03.independent.ie/style/celebrity/celebrity-news/article37866116.ece/097c2/AUTOCROP/w620/ipanews_cbc3aeeb-0628-4b80-8370-0cd43cbc3929_1" }],
    portraitData1: [{ "id": 1, "name": "Вася", "job": "QA", "photo": "https://cdn-03.independent.ie/style/celebrity/celebrity-news/article37866116.ece/097c2/AUTOCROP/w620/ipanews_cbc3aeeb-0628-4b80-8370-0cd43cbc3929_1" }, { "id": 2, "name": "Петя", "job": "Developer", "photo": "https://pmctvline2.files.wordpress.com/2018/10/game-of-thrones-peter-dinklage-tyrion-death-season-8-interview.jpg?w=620" }, { "id": 3, "name": "Вова", "job": "Senior Developer", "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcaeIWOmi62oncorhSKDzoBPIA7mF1QWUqgnFXKRTbaGHAsp8fUA" }, { "id": 4, "name": "Арчибальд", "job": "QA Lead", "photo": "https://cdn-static.denofgeek.com/sites/denofgeek/files/styles/main_wide/public/2018/05/game-of-thrones-season-1-recap.jpg?itok=ZwQDxPFR" }, { "id": 5, "name": "Клава", "job": "PM", "photo": "https://media.socastsrm.com/wordpress/wp-content/blogs.dir/873/files/2019/04/game-of-thrones-character-poster.jpg" }, { "id": 6, "name": "Дуся", "job": "DM", "photo": "https://pmcvariety.files.wordpress.com/2017/12/game-of-thrones-sansa.jpg?w=1000&h=563&crop=1" }, { "id": 7, "name": "Саманта", "job": "BA", "photo": "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/lena-headey-cersei-lannister-game-of-thrones-season-8-1553173898.jpg?resize=480:*" }, { "id": 8, "name": "Ядвига", "job": "Junior QA", "photo": "https://www.hbo.com/content/dam/hbodata/series/game-of-thrones/episodes/8/episodes/69/ep69-gamerevealed-1920x1080.jpg/_jcr_content/renditions/cq5dam.web.1200.675.jpeg" }],
    portraitData2: [{ "id": 9, "name": "Акакий", "job": "DevOps", "photo": "https://dwgyu36up6iuz.cloudfront.net/heru80fdn/image/upload/c_fill,d_placeholder_wired.png,fl_progressive,g_face,h_450,q_80,w_800/v1389040063/wired_alfie-allen-on-game-of-thrones.jpg" }, { "id": 10, "name": "Нестор", "job": "DB Expert", "photo": "https://kor.ill.in.ua/m/610x385/2031772.jpg" }, { "id": 11, "name": "Потап", "job": "Solutions Architect", "photo": "https://vignette.wikia.nocookie.net/gameofthrones/images/9/94/804_Ghost_Profile.png/revision/latest/scale-to-width-down/338?cb=20190506030424" }, { "id": 12, "name": "Платон", "job": "DB Expert", "photo": "https://cdn.maximonline.ru/08/4c/23/084c235db5d0d0dc05c3168d89c30865/665x374_1_6c90704c7d93e73a7b220326b1e3f4f3@674x379_0xac120005_18077754021529114221.jpg" }, { "id": 13, "name": "Ефросинья", "job": "Frontend Developer", "photo": "https://cdnimg.rg.ru/i/gallery/a310d529/1_220c7ba8.jpg" }, { "id": 14, "name": "Джонатан", "job": "Backend Developer", "photo": "https://s14.stc.all.kpcdn.net/share/i/12/7983901/inx960x640.jpg" }, { "id": 15, "name": "Грег", "job": "Грег", "photo": "https://vignette.wikia.nocookie.net/warrior/images/4/4d/Jorah-mormont-01-683x1024.jpg/revision/latest?cb=20160221123449&path-prefix=ru" }, { "id": 1, "name": "Вася", "job": "QA", "photo": "https://cdn-03.independent.ie/style/celebrity/celebrity-news/article37866116.ece/097c2/AUTOCROP/w620/ipanews_cbc3aeeb-0628-4b80-8370-0cd43cbc3929_1" }]
  };

  constructor(private http: HttpClient) { }

  getUserProfile() {
    return this.personInfo;
    // return this.http.get<any[]>('https://jsonplaceholder.typicode.com/users', {});
  }

  getClients() {
    return this.mockData;
  }
}
